export const AIRPORT_CITIES: Record<
  string,
  { city: string; metro?: string; country: string; countryCode: string }
> = {
  AMS: { city: 'Amsterdam', country: 'Netherlands', countryCode: 'NL' },
  ATL: { city: 'Atlanta', country: 'USA', countryCode: 'US' },
  AUS: { city: 'Austin', country: 'USA', countryCode: 'US' },
  BCN: { city: 'Barcelona', country: 'Spain', countryCode: 'ES' },
  BOS: { city: 'Boston', country: 'USA', countryCode: 'US' },
  CDG: { city: 'Paris', country: 'France', countryCode: 'FR' },
  CHS: { city: 'Charleston', country: 'USA', countryCode: 'US' },
  DEN: { city: 'Denver', country: 'USA', countryCode: 'US' },
  DFW: { city: 'Dallas', country: 'USA', countryCode: 'US' },
  DTW: { city: 'Detroit', country: 'USA', countryCode: 'US' },
  EWR: { city: 'Newark', metro: 'New York', country: 'USA', countryCode: 'US' },
  FCO: { city: 'Rome', country: 'Italy', countryCode: 'IT' },
  FLL: { city: 'Fort Lauderdale', country: 'USA', countryCode: 'US' },
  HND: { city: 'Tokyo', country: 'Japan', countryCode: 'JP' },
  ICN: { city: 'Seoul', country: 'South Korea', countryCode: 'KR' },
  JFK: { city: 'New York', metro: 'New York', country: 'USA', countryCode: 'US' },
  LAX: { city: 'Los Angeles', country: 'USA', countryCode: 'US' },
  LGA: { city: 'New York', metro: 'New York', country: 'USA', countryCode: 'US' },
  LHR: { city: 'London', country: 'UK', countryCode: 'GB' },
  LIN: { city: 'Milan', country: 'Italy', countryCode: 'IT' },
  MDW: { city: 'Chicago', metro: 'Chicago', country: 'USA', countryCode: 'US' },
  MIA: { city: 'Miami', country: 'USA', countryCode: 'US' },
  MSP: { city: 'Minneapolis', country: 'USA', countryCode: 'US' },
  MXP: { city: 'Milan', country: 'Italy', countryCode: 'IT' },
  NCE: { city: 'Nice', country: 'France', countryCode: 'FR' },
  NRT: { city: 'Tokyo', country: 'Japan', countryCode: 'JP' },
  ORD: { city: 'Chicago', country: 'USA', countryCode: 'US' },
  ORY: { city: 'Paris', country: 'France', countryCode: 'FR' },
  PDX: { city: 'Portland', country: 'USA', countryCode: 'US' },
  PEK: { city: 'Beijing', country: 'China', countryCode: 'CN' },
  PHX: { city: 'Phoenix', country: 'USA', countryCode: 'US' },
  PSP: { city: 'Palm Springs', country: 'USA', countryCode: 'US' },
  SAN: { city: 'San Diego', country: 'USA', countryCode: 'US' },
  SCL: { city: 'Santiago', country: 'Chile', countryCode: 'CL' },
  SEA: { city: 'Seattle', country: 'USA', countryCode: 'US' },
  SFO: { city: 'San Francisco', country: 'USA', countryCode: 'US' },
  SRQ: { city: 'Sarasota', country: 'USA', countryCode: 'US' },
  SXM: { city: 'Saint Maarten', country: 'Sint Maarten', countryCode: 'SX' },
  TLL: { city: 'Tallinn', country: 'Estonia', countryCode: 'EE' },
  TPA: { city: 'Tampa', country: 'USA', countryCode: 'US' },
  TRN: { city: 'Turin', country: 'Italy', countryCode: 'IT' },
}

export function getMetroArea(airportCode: string): string | null {
  const airport = AIRPORT_CITIES[airportCode.trim().toUpperCase()]
  return airport?.metro ?? null
}
