/**
 * Airport IATA code → IANA timezone lookup.
 * Covers ~50+ major hubs across Europe, North America, and Asia.
 * Unknown airports return null → caller falls back to floating time.
 */
const AIRPORT_TIMEZONES: Record<string, string> = {
  // ── Europe ──────────────────────────────────────────────────────────────
  LHR: 'Europe/London',
  LGW: 'Europe/London',
  STN: 'Europe/London',
  LTN: 'Europe/London',
  LCY: 'Europe/London',
  MAN: 'Europe/London',
  EDI: 'Europe/London',
  BHX: 'Europe/London',

  CDG: 'Europe/Paris',
  ORY: 'Europe/Paris',
  BVA: 'Europe/Paris',

  AMS: 'Europe/Amsterdam',
  BRU: 'Europe/Brussels',
  FRA: 'Europe/Berlin',
  MUC: 'Europe/Berlin',
  TXL: 'Europe/Berlin',
  BER: 'Europe/Berlin',
  DUS: 'Europe/Berlin',
  HAM: 'Europe/Berlin',
  CGN: 'Europe/Berlin',
  NUE: 'Europe/Berlin',
  STR: 'Europe/Berlin',

  MAD: 'Europe/Madrid',
  BCN: 'Europe/Madrid',
  PMI: 'Europe/Madrid',
  AGP: 'Europe/Madrid',
  VLC: 'Europe/Madrid',
  SVQ: 'Europe/Madrid',

  FCO: 'Europe/Rome',
  CIA: 'Europe/Rome',
  MXP: 'Europe/Rome',
  LIN: 'Europe/Rome',
  NAP: 'Europe/Rome',
  VCE: 'Europe/Rome',
  BLQ: 'Europe/Rome',
  CTA: 'Europe/Rome',

  ZRH: 'Europe/Zurich',
  GVA: 'Europe/Zurich',
  BSL: 'Europe/Zurich',

  VIE: 'Europe/Vienna',
  PRG: 'Europe/Prague',
  BUD: 'Europe/Budapest',
  WAW: 'Europe/Warsaw',
  KRK: 'Europe/Warsaw',

  ARN: 'Europe/Stockholm',
  GOT: 'Europe/Stockholm',
  CPH: 'Europe/Copenhagen',
  OSL: 'Europe/Oslo',
  HEL: 'Europe/Helsinki',

  TLL: 'Europe/Tallinn',
  RIX: 'Europe/Riga',
  VNO: 'Europe/Vilnius',

  LIS: 'Europe/Lisbon',
  OPO: 'Europe/Lisbon',
  FAO: 'Europe/Lisbon',

  ATH: 'Europe/Athens',
  SKG: 'Europe/Athens',
  HER: 'Europe/Athens',
  RHO: 'Europe/Athens',

  IST: 'Europe/Istanbul',
  SAW: 'Europe/Istanbul',
  AYT: 'Europe/Istanbul',

  DUB: 'Europe/Dublin',
  SNN: 'Europe/Dublin',

  LUX: 'Europe/Luxembourg',

  SVO: 'Europe/Moscow',
  DME: 'Europe/Moscow',
  VKO: 'Europe/Moscow',
  LED: 'Europe/Moscow',

  // ── North America ────────────────────────────────────────────────────────
  JFK: 'America/New_York',
  LGA: 'America/New_York',
  EWR: 'America/New_York',
  BOS: 'America/New_York',
  DCA: 'America/New_York',
  IAD: 'America/New_York',
  BWI: 'America/New_York',
  PHL: 'America/New_York',
  CLT: 'America/New_York',
  MIA: 'America/New_York',
  FLL: 'America/New_York',
  MCO: 'America/New_York',
  ATL: 'America/New_York',
  DTW: 'America/New_York',
  PIT: 'America/New_York',
  BNA: 'America/New_York',
  RDU: 'America/New_York',

  ORD: 'America/Chicago',
  MDW: 'America/Chicago',
  MSP: 'America/Chicago',
  MKE: 'America/Chicago',
  STL: 'America/Chicago',
  MSY: 'America/Chicago',
  AUS: 'America/Chicago',
  IAH: 'America/Chicago',
  HOU: 'America/Chicago',
  DAL: 'America/Chicago',
  DFW: 'America/Chicago',
  OKC: 'America/Chicago',
  MCI: 'America/Chicago',

  DEN: 'America/Denver',
  SLC: 'America/Denver',
  PHX: 'America/Phoenix',
  ABQ: 'America/Denver',
  TUS: 'America/Phoenix',

  LAX: 'America/Los_Angeles',
  SFO: 'America/Los_Angeles',
  SJC: 'America/Los_Angeles',
  OAK: 'America/Los_Angeles',
  SEA: 'America/Los_Angeles',
  PDX: 'America/Los_Angeles',
  LAS: 'America/Los_Angeles',
  SAN: 'America/Los_Angeles',
  SMF: 'America/Los_Angeles',
  BUR: 'America/Los_Angeles',
  ONT: 'America/Los_Angeles',

  YYZ: 'America/Toronto',
  YUL: 'America/Toronto',
  YOW: 'America/Toronto',
  YHZ: 'America/Halifax',
  YVR: 'America/Vancouver',
  YYC: 'America/Edmonton',
  YEG: 'America/Edmonton',
  YWG: 'America/Winnipeg',

  GRU: 'America/Sao_Paulo',
  GIG: 'America/Sao_Paulo',
  BSB: 'America/Sao_Paulo',
  EZE: 'America/Argentina/Buenos_Aires',
  BOG: 'America/Bogota',
  LIM: 'America/Lima',
  SCL: 'America/Santiago',
  MEX: 'America/Mexico_City',
  CUN: 'America/Cancun',
  PTY: 'America/Panama',

  // ── Asia-Pacific ─────────────────────────────────────────────────────────
  NRT: 'Asia/Tokyo',
  HND: 'Asia/Tokyo',
  KIX: 'Asia/Tokyo',
  NGO: 'Asia/Tokyo',
  CTS: 'Asia/Tokyo',
  FUK: 'Asia/Tokyo',

  ICN: 'Asia/Seoul',
  GMP: 'Asia/Seoul',
  PUS: 'Asia/Seoul',

  PEK: 'Asia/Shanghai',
  PKX: 'Asia/Shanghai',
  PVG: 'Asia/Shanghai',
  SHA: 'Asia/Shanghai',
  CAN: 'Asia/Shanghai',
  SZX: 'Asia/Shanghai',
  CTU: 'Asia/Shanghai',
  CSX: 'Asia/Shanghai',
  XIY: 'Asia/Shanghai',

  HKG: 'Asia/Hong_Kong',
  MFM: 'Asia/Macau',

  TPE: 'Asia/Taipei',
  KHH: 'Asia/Taipei',

  SIN: 'Asia/Singapore',
  KUL: 'Asia/Kuala_Lumpur',
  BKK: 'Asia/Bangkok',
  DMK: 'Asia/Bangkok',
  CNX: 'Asia/Bangkok',
  HKT: 'Asia/Bangkok',

  CGK: 'Asia/Jakarta',
  DPS: 'Asia/Makassar',

  MNL: 'Asia/Manila',
  CEB: 'Asia/Manila',

  HAN: 'Asia/Ho_Chi_Minh',
  SGN: 'Asia/Ho_Chi_Minh',

  DEL: 'Asia/Kolkata',
  BOM: 'Asia/Kolkata',
  MAA: 'Asia/Kolkata',
  CCU: 'Asia/Kolkata',
  BLR: 'Asia/Kolkata',
  HYD: 'Asia/Kolkata',
  AMD: 'Asia/Kolkata',
  GOI: 'Asia/Kolkata',

  KHI: 'Asia/Karachi',
  LHE: 'Asia/Karachi',
  ISB: 'Asia/Karachi',

  DXB: 'Asia/Dubai',
  AUH: 'Asia/Dubai',
  SHJ: 'Asia/Dubai',
  DOH: 'Asia/Qatar',
  KWI: 'Asia/Kuwait',
  BAH: 'Asia/Bahrain',
  RUH: 'Asia/Riyadh',
  JED: 'Asia/Riyadh',
  MED: 'Asia/Riyadh',
  MCT: 'Asia/Muscat',
  AMM: 'Asia/Amman',
  BEY: 'Asia/Beirut',
  TLV: 'Asia/Jerusalem',
  CAI: 'Africa/Cairo',

  THR: 'Asia/Tehran',
  IKA: 'Asia/Tehran',

  ALA: 'Asia/Almaty',
  TSE: 'Asia/Almaty',
  TAS: 'Asia/Tashkent',
  GYD: 'Asia/Baku',
  TBS: 'Asia/Tbilisi',
  EVN: 'Asia/Yerevan',

  // ── Africa ───────────────────────────────────────────────────────────────
  JNB: 'Africa/Johannesburg',
  CPT: 'Africa/Johannesburg',
  DUR: 'Africa/Johannesburg',
  NBO: 'Africa/Nairobi',
  ADD: 'Africa/Addis_Ababa',
  LOS: 'Africa/Lagos',
  ABV: 'Africa/Lagos',
  ACC: 'Africa/Accra',
  CMN: 'Africa/Casablanca',
  ALG: 'Africa/Algiers',
  TUN: 'Africa/Tunis',
  TIP: 'Africa/Tripoli',

  // ── Oceania ──────────────────────────────────────────────────────────────
  SYD: 'Australia/Sydney',
  MEL: 'Australia/Melbourne',
  BNE: 'Australia/Brisbane',
  PER: 'Australia/Perth',
  ADL: 'Australia/Adelaide',
  CBR: 'Australia/Sydney',
  OOL: 'Australia/Brisbane',
  CNS: 'Australia/Brisbane',
  AKL: 'Pacific/Auckland',
  WLG: 'Pacific/Auckland',
  CHC: 'Pacific/Auckland',
}

export function getAirportTimezone(airportCode: string): string | null {
  return AIRPORT_TIMEZONES[airportCode.toUpperCase()] ?? null
}

/**
 * Pre-built VTIMEZONE blocks for IANA zones referenced by the airport map.
 * Format: TZID → lines (without the outer BEGIN/END:VTIMEZONE wrappers).
 * Rules are kept simple — RRULE-based so they work for past & future dates.
 *
 * Zones without DST get only a STANDARD component.
 * EU zones follow: DST last SU of March 01:00 UTC → last SU of October 01:00 UTC
 * US zones follow: DST 2nd SU of March 02:00 → 1st SU of November 02:00
 */
const VTIMEZONE_BLOCKS: Record<string, string[]> = {
  // ── UTC ───────────────────────────────────────────────────────────────────
  'UTC': [
    'BEGIN:VTIMEZONE',
    'TZID:UTC',
    'BEGIN:STANDARD',
    'DTSTART:19700101T000000',
    'TZOFFSETFROM:+0000',
    'TZOFFSETTO:+0000',
    'TZNAME:UTC',
    'END:STANDARD',
    'END:VTIMEZONE',
  ],

  // ── Europe/London (GMT/BST) ───────────────────────────────────────────────
  'Europe/London': [
    'BEGIN:VTIMEZONE',
    'TZID:Europe/London',
    'BEGIN:STANDARD',
    'DTSTART:19701025T020000',
    'RRULE:FREQ=YEARLY;BYDAY=-1SU;BYMONTH=10',
    'TZOFFSETFROM:+0100',
    'TZOFFSETTO:+0000',
    'TZNAME:GMT',
    'END:STANDARD',
    'BEGIN:DAYLIGHT',
    'DTSTART:19700329T010000',
    'RRULE:FREQ=YEARLY;BYDAY=-1SU;BYMONTH=3',
    'TZOFFSETFROM:+0000',
    'TZOFFSETTO:+0100',
    'TZNAME:BST',
    'END:DAYLIGHT',
    'END:VTIMEZONE',
  ],

  // ── Europe/Dublin (GMT/IST) ───────────────────────────────────────────────
  'Europe/Dublin': [
    'BEGIN:VTIMEZONE',
    'TZID:Europe/Dublin',
    'BEGIN:STANDARD',
    'DTSTART:19701025T020000',
    'RRULE:FREQ=YEARLY;BYDAY=-1SU;BYMONTH=10',
    'TZOFFSETFROM:+0100',
    'TZOFFSETTO:+0000',
    'TZNAME:GMT',
    'END:STANDARD',
    'BEGIN:DAYLIGHT',
    'DTSTART:19700329T010000',
    'RRULE:FREQ=YEARLY;BYDAY=-1SU;BYMONTH=3',
    'TZOFFSETFROM:+0000',
    'TZOFFSETTO:+0100',
    'TZNAME:IST',
    'END:DAYLIGHT',
    'END:VTIMEZONE',
  ],

  // ── Europe/Lisbon (WET/WEST) ──────────────────────────────────────────────
  'Europe/Lisbon': [
    'BEGIN:VTIMEZONE',
    'TZID:Europe/Lisbon',
    'BEGIN:STANDARD',
    'DTSTART:19701025T020000',
    'RRULE:FREQ=YEARLY;BYDAY=-1SU;BYMONTH=10',
    'TZOFFSETFROM:+0100',
    'TZOFFSETTO:+0000',
    'TZNAME:WET',
    'END:STANDARD',
    'BEGIN:DAYLIGHT',
    'DTSTART:19700329T010000',
    'RRULE:FREQ=YEARLY;BYDAY=-1SU;BYMONTH=3',
    'TZOFFSETFROM:+0000',
    'TZOFFSETTO:+0100',
    'TZNAME:WEST',
    'END:DAYLIGHT',
    'END:VTIMEZONE',
  ],

  // EU CET/CEST zones (+1/+2): Paris, Berlin, Amsterdam, Brussels, Rome, Madrid,
  //   Vienna, Prague, Budapest, Warsaw, Stockholm, Copenhagen, Oslo, Luxembourg, Zurich
  ...([
    'Europe/Paris',
    'Europe/Berlin',
    'Europe/Amsterdam',
    'Europe/Brussels',
    'Europe/Rome',
    'Europe/Madrid',
    'Europe/Vienna',
    'Europe/Prague',
    'Europe/Budapest',
    'Europe/Warsaw',
    'Europe/Stockholm',
    'Europe/Copenhagen',
    'Europe/Oslo',
    'Europe/Luxembourg',
    'Europe/Zurich',
    'Europe/Tallinn',
  ].reduce<Record<string, string[]>>((acc, tzid) => {
    acc[tzid] = [
      `BEGIN:VTIMEZONE`,
      `TZID:${tzid}`,
      'BEGIN:STANDARD',
      'DTSTART:19701025T030000',
      'RRULE:FREQ=YEARLY;BYDAY=-1SU;BYMONTH=10',
      'TZOFFSETFROM:+0200',
      'TZOFFSETTO:+0100',
      'TZNAME:CET',
      'END:STANDARD',
      'BEGIN:DAYLIGHT',
      'DTSTART:19700329T020000',
      'RRULE:FREQ=YEARLY;BYDAY=-1SU;BYMONTH=3',
      'TZOFFSETFROM:+0100',
      'TZOFFSETTO:+0200',
      'TZNAME:CEST',
      'END:DAYLIGHT',
      'END:VTIMEZONE',
    ]
    return acc
  }, {})),

  // EET/EEST zones (+2/+3): Helsinki, Athens, Riga, Vilnius
  ...([
    'Europe/Helsinki',
    'Europe/Athens',
    'Europe/Riga',
    'Europe/Vilnius',
  ].reduce<Record<string, string[]>>((acc, tzid) => {
    acc[tzid] = [
      `BEGIN:VTIMEZONE`,
      `TZID:${tzid}`,
      'BEGIN:STANDARD',
      'DTSTART:19701025T040000',
      'RRULE:FREQ=YEARLY;BYDAY=-1SU;BYMONTH=10',
      'TZOFFSETFROM:+0300',
      'TZOFFSETTO:+0200',
      'TZNAME:EET',
      'END:STANDARD',
      'BEGIN:DAYLIGHT',
      'DTSTART:19700329T030000',
      'RRULE:FREQ=YEARLY;BYDAY=-1SU;BYMONTH=3',
      'TZOFFSETFROM:+0200',
      'TZOFFSETTO:+0300',
      'TZNAME:EEST',
      'END:DAYLIGHT',
      'END:VTIMEZONE',
    ]
    return acc
  }, {})),

  // Europe/Istanbul (+3, no DST since 2016)
  'Europe/Istanbul': [
    'BEGIN:VTIMEZONE',
    'TZID:Europe/Istanbul',
    'BEGIN:STANDARD',
    'DTSTART:19700101T000000',
    'TZOFFSETFROM:+0300',
    'TZOFFSETTO:+0300',
    'TZNAME:TRT',
    'END:STANDARD',
    'END:VTIMEZONE',
  ],

  // Europe/Moscow (+3, no DST)
  'Europe/Moscow': [
    'BEGIN:VTIMEZONE',
    'TZID:Europe/Moscow',
    'BEGIN:STANDARD',
    'DTSTART:19700101T000000',
    'TZOFFSETFROM:+0300',
    'TZOFFSETTO:+0300',
    'TZNAME:MSK',
    'END:STANDARD',
    'END:VTIMEZONE',
  ],

  // ── Americas ──────────────────────────────────────────────────────────────
  'America/New_York': [
    'BEGIN:VTIMEZONE',
    'TZID:America/New_York',
    'BEGIN:STANDARD',
    'DTSTART:19701101T020000',
    'RRULE:FREQ=YEARLY;BYDAY=1SU;BYMONTH=11',
    'TZOFFSETFROM:-0400',
    'TZOFFSETTO:-0500',
    'TZNAME:EST',
    'END:STANDARD',
    'BEGIN:DAYLIGHT',
    'DTSTART:19700308T020000',
    'RRULE:FREQ=YEARLY;BYDAY=2SU;BYMONTH=3',
    'TZOFFSETFROM:-0500',
    'TZOFFSETTO:-0400',
    'TZNAME:EDT',
    'END:DAYLIGHT',
    'END:VTIMEZONE',
  ],

  'America/Toronto': [
    'BEGIN:VTIMEZONE',
    'TZID:America/Toronto',
    'BEGIN:STANDARD',
    'DTSTART:19701101T020000',
    'RRULE:FREQ=YEARLY;BYDAY=1SU;BYMONTH=11',
    'TZOFFSETFROM:-0400',
    'TZOFFSETTO:-0500',
    'TZNAME:EST',
    'END:STANDARD',
    'BEGIN:DAYLIGHT',
    'DTSTART:19700308T020000',
    'RRULE:FREQ=YEARLY;BYDAY=2SU;BYMONTH=3',
    'TZOFFSETFROM:-0500',
    'TZOFFSETTO:-0400',
    'TZNAME:EDT',
    'END:DAYLIGHT',
    'END:VTIMEZONE',
  ],

  'America/Halifax': [
    'BEGIN:VTIMEZONE',
    'TZID:America/Halifax',
    'BEGIN:STANDARD',
    'DTSTART:19701101T020000',
    'RRULE:FREQ=YEARLY;BYDAY=1SU;BYMONTH=11',
    'TZOFFSETFROM:-0300',
    'TZOFFSETTO:-0400',
    'TZNAME:AST',
    'END:STANDARD',
    'BEGIN:DAYLIGHT',
    'DTSTART:19700308T020000',
    'RRULE:FREQ=YEARLY;BYDAY=2SU;BYMONTH=3',
    'TZOFFSETFROM:-0400',
    'TZOFFSETTO:-0300',
    'TZNAME:ADT',
    'END:DAYLIGHT',
    'END:VTIMEZONE',
  ],

  'America/Chicago': [
    'BEGIN:VTIMEZONE',
    'TZID:America/Chicago',
    'BEGIN:STANDARD',
    'DTSTART:19701101T020000',
    'RRULE:FREQ=YEARLY;BYDAY=1SU;BYMONTH=11',
    'TZOFFSETFROM:-0500',
    'TZOFFSETTO:-0600',
    'TZNAME:CST',
    'END:STANDARD',
    'BEGIN:DAYLIGHT',
    'DTSTART:19700308T020000',
    'RRULE:FREQ=YEARLY;BYDAY=2SU;BYMONTH=3',
    'TZOFFSETFROM:-0600',
    'TZOFFSETTO:-0500',
    'TZNAME:CDT',
    'END:DAYLIGHT',
    'END:VTIMEZONE',
  ],

  'America/Winnipeg': [
    'BEGIN:VTIMEZONE',
    'TZID:America/Winnipeg',
    'BEGIN:STANDARD',
    'DTSTART:19701101T020000',
    'RRULE:FREQ=YEARLY;BYDAY=1SU;BYMONTH=11',
    'TZOFFSETFROM:-0500',
    'TZOFFSETTO:-0600',
    'TZNAME:CST',
    'END:STANDARD',
    'BEGIN:DAYLIGHT',
    'DTSTART:19700308T020000',
    'RRULE:FREQ=YEARLY;BYDAY=2SU;BYMONTH=3',
    'TZOFFSETFROM:-0600',
    'TZOFFSETTO:-0500',
    'TZNAME:CDT',
    'END:DAYLIGHT',
    'END:VTIMEZONE',
  ],

  'America/Denver': [
    'BEGIN:VTIMEZONE',
    'TZID:America/Denver',
    'BEGIN:STANDARD',
    'DTSTART:19701101T020000',
    'RRULE:FREQ=YEARLY;BYDAY=1SU;BYMONTH=11',
    'TZOFFSETFROM:-0600',
    'TZOFFSETTO:-0700',
    'TZNAME:MST',
    'END:STANDARD',
    'BEGIN:DAYLIGHT',
    'DTSTART:19700308T020000',
    'RRULE:FREQ=YEARLY;BYDAY=2SU;BYMONTH=3',
    'TZOFFSETFROM:-0700',
    'TZOFFSETTO:-0600',
    'TZNAME:MDT',
    'END:DAYLIGHT',
    'END:VTIMEZONE',
  ],

  'America/Edmonton': [
    'BEGIN:VTIMEZONE',
    'TZID:America/Edmonton',
    'BEGIN:STANDARD',
    'DTSTART:19701101T020000',
    'RRULE:FREQ=YEARLY;BYDAY=1SU;BYMONTH=11',
    'TZOFFSETFROM:-0600',
    'TZOFFSETTO:-0700',
    'TZNAME:MST',
    'END:STANDARD',
    'BEGIN:DAYLIGHT',
    'DTSTART:19700308T020000',
    'RRULE:FREQ=YEARLY;BYDAY=2SU;BYMONTH=3',
    'TZOFFSETFROM:-0700',
    'TZOFFSETTO:-0600',
    'TZNAME:MDT',
    'END:DAYLIGHT',
    'END:VTIMEZONE',
  ],

  // Phoenix has no DST
  'America/Phoenix': [
    'BEGIN:VTIMEZONE',
    'TZID:America/Phoenix',
    'BEGIN:STANDARD',
    'DTSTART:19700101T000000',
    'TZOFFSETFROM:-0700',
    'TZOFFSETTO:-0700',
    'TZNAME:MST',
    'END:STANDARD',
    'END:VTIMEZONE',
  ],

  'America/Los_Angeles': [
    'BEGIN:VTIMEZONE',
    'TZID:America/Los_Angeles',
    'BEGIN:STANDARD',
    'DTSTART:19701101T020000',
    'RRULE:FREQ=YEARLY;BYDAY=1SU;BYMONTH=11',
    'TZOFFSETFROM:-0700',
    'TZOFFSETTO:-0800',
    'TZNAME:PST',
    'END:STANDARD',
    'BEGIN:DAYLIGHT',
    'DTSTART:19700308T020000',
    'RRULE:FREQ=YEARLY;BYDAY=2SU;BYMONTH=3',
    'TZOFFSETFROM:-0800',
    'TZOFFSETTO:-0700',
    'TZNAME:PDT',
    'END:DAYLIGHT',
    'END:VTIMEZONE',
  ],

  'America/Vancouver': [
    'BEGIN:VTIMEZONE',
    'TZID:America/Vancouver',
    'BEGIN:STANDARD',
    'DTSTART:19701101T020000',
    'RRULE:FREQ=YEARLY;BYDAY=1SU;BYMONTH=11',
    'TZOFFSETFROM:-0700',
    'TZOFFSETTO:-0800',
    'TZNAME:PST',
    'END:STANDARD',
    'BEGIN:DAYLIGHT',
    'DTSTART:19700308T020000',
    'RRULE:FREQ=YEARLY;BYDAY=2SU;BYMONTH=3',
    'TZOFFSETFROM:-0800',
    'TZOFFSETTO:-0700',
    'TZNAME:PDT',
    'END:DAYLIGHT',
    'END:VTIMEZONE',
  ],

  // No-DST Americas
  'America/Sao_Paulo': [
    'BEGIN:VTIMEZONE',
    'TZID:America/Sao_Paulo',
    'BEGIN:STANDARD',
    'DTSTART:19700101T000000',
    'TZOFFSETFROM:-0300',
    'TZOFFSETTO:-0300',
    'TZNAME:BRT',
    'END:STANDARD',
    'END:VTIMEZONE',
  ],

  'America/Argentina/Buenos_Aires': [
    'BEGIN:VTIMEZONE',
    'TZID:America/Argentina/Buenos_Aires',
    'BEGIN:STANDARD',
    'DTSTART:19700101T000000',
    'TZOFFSETFROM:-0300',
    'TZOFFSETTO:-0300',
    'TZNAME:ART',
    'END:STANDARD',
    'END:VTIMEZONE',
  ],

  'America/Bogota': [
    'BEGIN:VTIMEZONE',
    'TZID:America/Bogota',
    'BEGIN:STANDARD',
    'DTSTART:19700101T000000',
    'TZOFFSETFROM:-0500',
    'TZOFFSETTO:-0500',
    'TZNAME:COT',
    'END:STANDARD',
    'END:VTIMEZONE',
  ],

  'America/Lima': [
    'BEGIN:VTIMEZONE',
    'TZID:America/Lima',
    'BEGIN:STANDARD',
    'DTSTART:19700101T000000',
    'TZOFFSETFROM:-0500',
    'TZOFFSETTO:-0500',
    'TZNAME:PET',
    'END:STANDARD',
    'END:VTIMEZONE',
  ],

  'America/Santiago': [
    'BEGIN:VTIMEZONE',
    'TZID:America/Santiago',
    'BEGIN:STANDARD',
    'DTSTART:19700101T000000',
    'TZOFFSETFROM:-0300',
    'TZOFFSETTO:-0300',
    'TZNAME:CLT',
    'END:STANDARD',
    'END:VTIMEZONE',
  ],

  'America/Mexico_City': [
    'BEGIN:VTIMEZONE',
    'TZID:America/Mexico_City',
    'BEGIN:STANDARD',
    'DTSTART:19700101T000000',
    'TZOFFSETFROM:-0600',
    'TZOFFSETTO:-0600',
    'TZNAME:CST',
    'END:STANDARD',
    'END:VTIMEZONE',
  ],

  'America/Cancun': [
    'BEGIN:VTIMEZONE',
    'TZID:America/Cancun',
    'BEGIN:STANDARD',
    'DTSTART:19700101T000000',
    'TZOFFSETFROM:-0500',
    'TZOFFSETTO:-0500',
    'TZNAME:EST',
    'END:STANDARD',
    'END:VTIMEZONE',
  ],

  'America/Panama': [
    'BEGIN:VTIMEZONE',
    'TZID:America/Panama',
    'BEGIN:STANDARD',
    'DTSTART:19700101T000000',
    'TZOFFSETFROM:-0500',
    'TZOFFSETTO:-0500',
    'TZNAME:EST',
    'END:STANDARD',
    'END:VTIMEZONE',
  ],

  // ── Asia / No DST ────────────────────────────────────────────────────────
  'Asia/Tokyo': [
    'BEGIN:VTIMEZONE',
    'TZID:Asia/Tokyo',
    'BEGIN:STANDARD',
    'DTSTART:19700101T000000',
    'TZOFFSETFROM:+0900',
    'TZOFFSETTO:+0900',
    'TZNAME:JST',
    'END:STANDARD',
    'END:VTIMEZONE',
  ],

  'Asia/Seoul': [
    'BEGIN:VTIMEZONE',
    'TZID:Asia/Seoul',
    'BEGIN:STANDARD',
    'DTSTART:19700101T000000',
    'TZOFFSETFROM:+0900',
    'TZOFFSETTO:+0900',
    'TZNAME:KST',
    'END:STANDARD',
    'END:VTIMEZONE',
  ],

  'Asia/Shanghai': [
    'BEGIN:VTIMEZONE',
    'TZID:Asia/Shanghai',
    'BEGIN:STANDARD',
    'DTSTART:19700101T000000',
    'TZOFFSETFROM:+0800',
    'TZOFFSETTO:+0800',
    'TZNAME:CST',
    'END:STANDARD',
    'END:VTIMEZONE',
  ],

  'Asia/Hong_Kong': [
    'BEGIN:VTIMEZONE',
    'TZID:Asia/Hong_Kong',
    'BEGIN:STANDARD',
    'DTSTART:19700101T000000',
    'TZOFFSETFROM:+0800',
    'TZOFFSETTO:+0800',
    'TZNAME:HKT',
    'END:STANDARD',
    'END:VTIMEZONE',
  ],

  'Asia/Macau': [
    'BEGIN:VTIMEZONE',
    'TZID:Asia/Macau',
    'BEGIN:STANDARD',
    'DTSTART:19700101T000000',
    'TZOFFSETFROM:+0800',
    'TZOFFSETTO:+0800',
    'TZNAME:CST',
    'END:STANDARD',
    'END:VTIMEZONE',
  ],

  'Asia/Taipei': [
    'BEGIN:VTIMEZONE',
    'TZID:Asia/Taipei',
    'BEGIN:STANDARD',
    'DTSTART:19700101T000000',
    'TZOFFSETFROM:+0800',
    'TZOFFSETTO:+0800',
    'TZNAME:CST',
    'END:STANDARD',
    'END:VTIMEZONE',
  ],

  'Asia/Singapore': [
    'BEGIN:VTIMEZONE',
    'TZID:Asia/Singapore',
    'BEGIN:STANDARD',
    'DTSTART:19700101T000000',
    'TZOFFSETFROM:+0800',
    'TZOFFSETTO:+0800',
    'TZNAME:SGT',
    'END:STANDARD',
    'END:VTIMEZONE',
  ],

  'Asia/Kuala_Lumpur': [
    'BEGIN:VTIMEZONE',
    'TZID:Asia/Kuala_Lumpur',
    'BEGIN:STANDARD',
    'DTSTART:19700101T000000',
    'TZOFFSETFROM:+0800',
    'TZOFFSETTO:+0800',
    'TZNAME:MYT',
    'END:STANDARD',
    'END:VTIMEZONE',
  ],

  'Asia/Bangkok': [
    'BEGIN:VTIMEZONE',
    'TZID:Asia/Bangkok',
    'BEGIN:STANDARD',
    'DTSTART:19700101T000000',
    'TZOFFSETFROM:+0700',
    'TZOFFSETTO:+0700',
    'TZNAME:ICT',
    'END:STANDARD',
    'END:VTIMEZONE',
  ],

  'Asia/Jakarta': [
    'BEGIN:VTIMEZONE',
    'TZID:Asia/Jakarta',
    'BEGIN:STANDARD',
    'DTSTART:19700101T000000',
    'TZOFFSETFROM:+0700',
    'TZOFFSETTO:+0700',
    'TZNAME:WIB',
    'END:STANDARD',
    'END:VTIMEZONE',
  ],

  'Asia/Makassar': [
    'BEGIN:VTIMEZONE',
    'TZID:Asia/Makassar',
    'BEGIN:STANDARD',
    'DTSTART:19700101T000000',
    'TZOFFSETFROM:+0800',
    'TZOFFSETTO:+0800',
    'TZNAME:WITA',
    'END:STANDARD',
    'END:VTIMEZONE',
  ],

  'Asia/Manila': [
    'BEGIN:VTIMEZONE',
    'TZID:Asia/Manila',
    'BEGIN:STANDARD',
    'DTSTART:19700101T000000',
    'TZOFFSETFROM:+0800',
    'TZOFFSETTO:+0800',
    'TZNAME:PHT',
    'END:STANDARD',
    'END:VTIMEZONE',
  ],

  'Asia/Ho_Chi_Minh': [
    'BEGIN:VTIMEZONE',
    'TZID:Asia/Ho_Chi_Minh',
    'BEGIN:STANDARD',
    'DTSTART:19700101T000000',
    'TZOFFSETFROM:+0700',
    'TZOFFSETTO:+0700',
    'TZNAME:ICT',
    'END:STANDARD',
    'END:VTIMEZONE',
  ],

  'Asia/Kolkata': [
    'BEGIN:VTIMEZONE',
    'TZID:Asia/Kolkata',
    'BEGIN:STANDARD',
    'DTSTART:19700101T000000',
    'TZOFFSETFROM:+0530',
    'TZOFFSETTO:+0530',
    'TZNAME:IST',
    'END:STANDARD',
    'END:VTIMEZONE',
  ],

  'Asia/Karachi': [
    'BEGIN:VTIMEZONE',
    'TZID:Asia/Karachi',
    'BEGIN:STANDARD',
    'DTSTART:19700101T000000',
    'TZOFFSETFROM:+0500',
    'TZOFFSETTO:+0500',
    'TZNAME:PKT',
    'END:STANDARD',
    'END:VTIMEZONE',
  ],

  'Asia/Dubai': [
    'BEGIN:VTIMEZONE',
    'TZID:Asia/Dubai',
    'BEGIN:STANDARD',
    'DTSTART:19700101T000000',
    'TZOFFSETFROM:+0400',
    'TZOFFSETTO:+0400',
    'TZNAME:GST',
    'END:STANDARD',
    'END:VTIMEZONE',
  ],

  'Asia/Qatar': [
    'BEGIN:VTIMEZONE',
    'TZID:Asia/Qatar',
    'BEGIN:STANDARD',
    'DTSTART:19700101T000000',
    'TZOFFSETFROM:+0300',
    'TZOFFSETTO:+0300',
    'TZNAME:AST',
    'END:STANDARD',
    'END:VTIMEZONE',
  ],

  'Asia/Kuwait': [
    'BEGIN:VTIMEZONE',
    'TZID:Asia/Kuwait',
    'BEGIN:STANDARD',
    'DTSTART:19700101T000000',
    'TZOFFSETFROM:+0300',
    'TZOFFSETTO:+0300',
    'TZNAME:AST',
    'END:STANDARD',
    'END:VTIMEZONE',
  ],

  'Asia/Bahrain': [
    'BEGIN:VTIMEZONE',
    'TZID:Asia/Bahrain',
    'BEGIN:STANDARD',
    'DTSTART:19700101T000000',
    'TZOFFSETFROM:+0300',
    'TZOFFSETTO:+0300',
    'TZNAME:AST',
    'END:STANDARD',
    'END:VTIMEZONE',
  ],

  'Asia/Riyadh': [
    'BEGIN:VTIMEZONE',
    'TZID:Asia/Riyadh',
    'BEGIN:STANDARD',
    'DTSTART:19700101T000000',
    'TZOFFSETFROM:+0300',
    'TZOFFSETTO:+0300',
    'TZNAME:AST',
    'END:STANDARD',
    'END:VTIMEZONE',
  ],

  'Asia/Muscat': [
    'BEGIN:VTIMEZONE',
    'TZID:Asia/Muscat',
    'BEGIN:STANDARD',
    'DTSTART:19700101T000000',
    'TZOFFSETFROM:+0400',
    'TZOFFSETTO:+0400',
    'TZNAME:GST',
    'END:STANDARD',
    'END:VTIMEZONE',
  ],

  'Asia/Amman': [
    'BEGIN:VTIMEZONE',
    'TZID:Asia/Amman',
    'BEGIN:STANDARD',
    'DTSTART:19700101T000000',
    'TZOFFSETFROM:+0300',
    'TZOFFSETTO:+0300',
    'TZNAME:EAT',
    'END:STANDARD',
    'END:VTIMEZONE',
  ],

  'Asia/Beirut': [
    'BEGIN:VTIMEZONE',
    'TZID:Asia/Beirut',
    'BEGIN:STANDARD',
    'DTSTART:19701025T030000',
    'RRULE:FREQ=YEARLY;BYDAY=-1SU;BYMONTH=10',
    'TZOFFSETFROM:+0300',
    'TZOFFSETTO:+0200',
    'TZNAME:EET',
    'END:STANDARD',
    'BEGIN:DAYLIGHT',
    'DTSTART:19700329T000000',
    'RRULE:FREQ=YEARLY;BYDAY=-1SU;BYMONTH=3',
    'TZOFFSETFROM:+0200',
    'TZOFFSETTO:+0300',
    'TZNAME:EEST',
    'END:DAYLIGHT',
    'END:VTIMEZONE',
  ],

  'Asia/Jerusalem': [
    'BEGIN:VTIMEZONE',
    'TZID:Asia/Jerusalem',
    'BEGIN:STANDARD',
    'DTSTART:19700101T000000',
    'TZOFFSETFROM:+0200',
    'TZOFFSETTO:+0200',
    'TZNAME:IST',
    'END:STANDARD',
    'END:VTIMEZONE',
  ],

  'Asia/Tehran': [
    'BEGIN:VTIMEZONE',
    'TZID:Asia/Tehran',
    'BEGIN:STANDARD',
    'DTSTART:19700101T000000',
    'TZOFFSETFROM:+0330',
    'TZOFFSETTO:+0330',
    'TZNAME:IRST',
    'END:STANDARD',
    'END:VTIMEZONE',
  ],

  'Asia/Almaty': [
    'BEGIN:VTIMEZONE',
    'TZID:Asia/Almaty',
    'BEGIN:STANDARD',
    'DTSTART:19700101T000000',
    'TZOFFSETFROM:+0600',
    'TZOFFSETTO:+0600',
    'TZNAME:ALMT',
    'END:STANDARD',
    'END:VTIMEZONE',
  ],

  'Asia/Tashkent': [
    'BEGIN:VTIMEZONE',
    'TZID:Asia/Tashkent',
    'BEGIN:STANDARD',
    'DTSTART:19700101T000000',
    'TZOFFSETFROM:+0500',
    'TZOFFSETTO:+0500',
    'TZNAME:UZT',
    'END:STANDARD',
    'END:VTIMEZONE',
  ],

  'Asia/Baku': [
    'BEGIN:VTIMEZONE',
    'TZID:Asia/Baku',
    'BEGIN:STANDARD',
    'DTSTART:19700101T000000',
    'TZOFFSETFROM:+0400',
    'TZOFFSETTO:+0400',
    'TZNAME:AZT',
    'END:STANDARD',
    'END:VTIMEZONE',
  ],

  'Asia/Tbilisi': [
    'BEGIN:VTIMEZONE',
    'TZID:Asia/Tbilisi',
    'BEGIN:STANDARD',
    'DTSTART:19700101T000000',
    'TZOFFSETFROM:+0400',
    'TZOFFSETTO:+0400',
    'TZNAME:GET',
    'END:STANDARD',
    'END:VTIMEZONE',
  ],

  'Asia/Yerevan': [
    'BEGIN:VTIMEZONE',
    'TZID:Asia/Yerevan',
    'BEGIN:STANDARD',
    'DTSTART:19700101T000000',
    'TZOFFSETFROM:+0400',
    'TZOFFSETTO:+0400',
    'TZNAME:AMT',
    'END:STANDARD',
    'END:VTIMEZONE',
  ],

  // ── Africa ────────────────────────────────────────────────────────────────
  'Africa/Cairo': [
    'BEGIN:VTIMEZONE',
    'TZID:Africa/Cairo',
    'BEGIN:STANDARD',
    'DTSTART:19700101T000000',
    'TZOFFSETFROM:+0200',
    'TZOFFSETTO:+0200',
    'TZNAME:EET',
    'END:STANDARD',
    'END:VTIMEZONE',
  ],

  'Africa/Johannesburg': [
    'BEGIN:VTIMEZONE',
    'TZID:Africa/Johannesburg',
    'BEGIN:STANDARD',
    'DTSTART:19700101T000000',
    'TZOFFSETFROM:+0200',
    'TZOFFSETTO:+0200',
    'TZNAME:SAST',
    'END:STANDARD',
    'END:VTIMEZONE',
  ],

  'Africa/Nairobi': [
    'BEGIN:VTIMEZONE',
    'TZID:Africa/Nairobi',
    'BEGIN:STANDARD',
    'DTSTART:19700101T000000',
    'TZOFFSETFROM:+0300',
    'TZOFFSETTO:+0300',
    'TZNAME:EAT',
    'END:STANDARD',
    'END:VTIMEZONE',
  ],

  'Africa/Addis_Ababa': [
    'BEGIN:VTIMEZONE',
    'TZID:Africa/Addis_Ababa',
    'BEGIN:STANDARD',
    'DTSTART:19700101T000000',
    'TZOFFSETFROM:+0300',
    'TZOFFSETTO:+0300',
    'TZNAME:EAT',
    'END:STANDARD',
    'END:VTIMEZONE',
  ],

  'Africa/Lagos': [
    'BEGIN:VTIMEZONE',
    'TZID:Africa/Lagos',
    'BEGIN:STANDARD',
    'DTSTART:19700101T000000',
    'TZOFFSETFROM:+0100',
    'TZOFFSETTO:+0100',
    'TZNAME:WAT',
    'END:STANDARD',
    'END:VTIMEZONE',
  ],

  'Africa/Accra': [
    'BEGIN:VTIMEZONE',
    'TZID:Africa/Accra',
    'BEGIN:STANDARD',
    'DTSTART:19700101T000000',
    'TZOFFSETFROM:+0000',
    'TZOFFSETTO:+0000',
    'TZNAME:GMT',
    'END:STANDARD',
    'END:VTIMEZONE',
  ],

  'Africa/Casablanca': [
    'BEGIN:VTIMEZONE',
    'TZID:Africa/Casablanca',
    'BEGIN:STANDARD',
    'DTSTART:19700101T000000',
    'TZOFFSETFROM:+0100',
    'TZOFFSETTO:+0100',
    'TZNAME:WET',
    'END:STANDARD',
    'END:VTIMEZONE',
  ],

  'Africa/Algiers': [
    'BEGIN:VTIMEZONE',
    'TZID:Africa/Algiers',
    'BEGIN:STANDARD',
    'DTSTART:19700101T000000',
    'TZOFFSETFROM:+0100',
    'TZOFFSETTO:+0100',
    'TZNAME:CET',
    'END:STANDARD',
    'END:VTIMEZONE',
  ],

  'Africa/Tunis': [
    'BEGIN:VTIMEZONE',
    'TZID:Africa/Tunis',
    'BEGIN:STANDARD',
    'DTSTART:19700101T000000',
    'TZOFFSETFROM:+0100',
    'TZOFFSETTO:+0100',
    'TZNAME:CET',
    'END:STANDARD',
    'END:VTIMEZONE',
  ],

  'Africa/Tripoli': [
    'BEGIN:VTIMEZONE',
    'TZID:Africa/Tripoli',
    'BEGIN:STANDARD',
    'DTSTART:19700101T000000',
    'TZOFFSETFROM:+0200',
    'TZOFFSETTO:+0200',
    'TZNAME:EET',
    'END:STANDARD',
    'END:VTIMEZONE',
  ],

  // ── Oceania ───────────────────────────────────────────────────────────────
  'Australia/Sydney': [
    'BEGIN:VTIMEZONE',
    'TZID:Australia/Sydney',
    'BEGIN:STANDARD',
    'DTSTART:19700405T030000',
    'RRULE:FREQ=YEARLY;BYDAY=1SU;BYMONTH=4',
    'TZOFFSETFROM:+1100',
    'TZOFFSETTO:+1000',
    'TZNAME:AEST',
    'END:STANDARD',
    'BEGIN:DAYLIGHT',
    'DTSTART:19701004T020000',
    'RRULE:FREQ=YEARLY;BYDAY=1SU;BYMONTH=10',
    'TZOFFSETFROM:+1000',
    'TZOFFSETTO:+1100',
    'TZNAME:AEDT',
    'END:DAYLIGHT',
    'END:VTIMEZONE',
  ],

  'Australia/Melbourne': [
    'BEGIN:VTIMEZONE',
    'TZID:Australia/Melbourne',
    'BEGIN:STANDARD',
    'DTSTART:19700405T030000',
    'RRULE:FREQ=YEARLY;BYDAY=1SU;BYMONTH=4',
    'TZOFFSETFROM:+1100',
    'TZOFFSETTO:+1000',
    'TZNAME:AEST',
    'END:STANDARD',
    'BEGIN:DAYLIGHT',
    'DTSTART:19701004T020000',
    'RRULE:FREQ=YEARLY;BYDAY=1SU;BYMONTH=10',
    'TZOFFSETFROM:+1000',
    'TZOFFSETTO:+1100',
    'TZNAME:AEDT',
    'END:DAYLIGHT',
    'END:VTIMEZONE',
  ],

  'Australia/Brisbane': [
    'BEGIN:VTIMEZONE',
    'TZID:Australia/Brisbane',
    'BEGIN:STANDARD',
    'DTSTART:19700101T000000',
    'TZOFFSETFROM:+1000',
    'TZOFFSETTO:+1000',
    'TZNAME:AEST',
    'END:STANDARD',
    'END:VTIMEZONE',
  ],

  'Australia/Perth': [
    'BEGIN:VTIMEZONE',
    'TZID:Australia/Perth',
    'BEGIN:STANDARD',
    'DTSTART:19700101T000000',
    'TZOFFSETFROM:+0800',
    'TZOFFSETTO:+0800',
    'TZNAME:AWST',
    'END:STANDARD',
    'END:VTIMEZONE',
  ],

  'Australia/Adelaide': [
    'BEGIN:VTIMEZONE',
    'TZID:Australia/Adelaide',
    'BEGIN:STANDARD',
    'DTSTART:19700405T030000',
    'RRULE:FREQ=YEARLY;BYDAY=1SU;BYMONTH=4',
    'TZOFFSETFROM:+1030',
    'TZOFFSETTO:+0930',
    'TZNAME:ACST',
    'END:STANDARD',
    'BEGIN:DAYLIGHT',
    'DTSTART:19701004T020000',
    'RRULE:FREQ=YEARLY;BYDAY=1SU;BYMONTH=10',
    'TZOFFSETFROM:+0930',
    'TZOFFSETTO:+1030',
    'TZNAME:ACDT',
    'END:DAYLIGHT',
    'END:VTIMEZONE',
  ],

  'Pacific/Auckland': [
    'BEGIN:VTIMEZONE',
    'TZID:Pacific/Auckland',
    'BEGIN:STANDARD',
    'DTSTART:19700405T030000',
    'RRULE:FREQ=YEARLY;BYDAY=1SU;BYMONTH=4',
    'TZOFFSETFROM:+1300',
    'TZOFFSETTO:+1200',
    'TZNAME:NZST',
    'END:STANDARD',
    'BEGIN:DAYLIGHT',
    'DTSTART:19700927T020000',
    'RRULE:FREQ=YEARLY;BYDAY=-1SU;BYMONTH=9',
    'TZOFFSETFROM:+1200',
    'TZOFFSETTO:+1300',
    'TZNAME:NZDT',
    'END:DAYLIGHT',
    'END:VTIMEZONE',
  ],
}

/**
 * Return the VTIMEZONE block lines for a given IANA timezone ID,
 * or null if we don't have a definition for it.
 */
export function getVTimezoneBlock(tzid: string): string[] | null {
  return VTIMEZONE_BLOCKS[tzid] ?? null
}
